name: Bug report
description: Report a reproducible problem in Materialist
title: "[Bug] "
labels: ["kind/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report. Please provide enough detail for maintainers to reproduce the issue quickly.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-sentence description of the bug
      placeholder: Feed sorting resets after refresh
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - papers
        - forum
        - showcase
        - jobs
        - auth/profile
        - api/backend
        - deployment
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact step-by-step instructions
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Node version
      placeholder: macOS 15.3, Chrome 123, Node 22
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste stack traces, request ids, screenshots, or videos

